const products = [
  {
    id: 101,
    title: "Kids Cotton T-Shirt Dino",
    price: 14.99,
    description: "Soft cotton T-shirt with dinosaur print for everyday play.",
    category: "boys clothing",
    image: "/d1n2nsg9oh61u9a3qiq0.jpg",
    rating: { rate: 4.7, count: 180 },
  },
  {
    id: 102,
    title: "Girls Floral Summer Dress",
    price: 22.5,
    description: "Lightweight floral dress with breathable fabric for warm days.",
    category: "girls clothing",
    image: "/d66e6pjq345uoeq1u0mg.jpg",
    rating: { rate: 4.8, count: 145 },
  },
  {
    id: 103,
    title: "Toddler Cozy Hoodie",
    price: 26.0,
    description: "Warm hoodie with front pocket and soft brushed inner layer.",
    category: "toddler clothing",
    image: "/d047nvtpb7f46s882adg.jpg",
    rating: { rate: 4.6, count: 95 },
  },
  {
    id: 104,
    title: "Kids Denim Overalls",
    price: 31.99,
    description: "Durable denim overalls with adjustable straps and side buttons.",
    category: "unisex kids clothing",
    image: "/d6e1nntv2sjv9oet99q0.jpg",
    rating: { rate: 4.5, count: 132 },
  },
  {
    id: 105,
    title: "Boys Sport Shorts Set",
    price: 19.99,
    description: "Two-piece shorts set designed for active play and comfort.",
    category: "boys clothing",
    image: "/d0494lmi4n37npapracg.jpg",
    rating: { rate: 4.4, count: 88 },
  },
  {
    id: 106,
    title: "Girls Knit Cardigan",
    price: 24.99,
    description: "Button-up knit cardigan, easy to layer for school or outings.",
    category: "girls clothing",
    image: "/d18kksb3uvppu2ac7rsg.jpg",
    rating: { rate: 4.9, count: 210 },
  },
  {
    id: 107,
    title: "Baby Romper 3-Pack",
    price: 17.49,
    description: "Set of three baby rompers with snap buttons and stretch fit.",
    category: "baby clothing",
    image: "/d1n2nsg9oh61u9a3qiq0.jpg",
    rating: { rate: 4.7, count: 170 },
  },
  {
    id: 108,
    title: "Kids Rain Jacket",
    price: 29.5,
    description: "Water-resistant jacket with hood and reflective details.",
    category: "unisex kids clothing",
    image: "/d66e6pjq345uoeq1u0mg.jpg",
    rating: { rate: 4.3, count: 76 },
  },
];

export default products;
