const products = [
  {
    id: 1001,
    title: "Детская хлопковая футболка «Дино»",
    price: 14.99,
    description: "Мягкая хлопковая футболка с принтом динозавра для ежедневных игр.",
    category: "boys clothing",
    image: "/d1n2nsg9oh61u9a3qiq0.jpg",
    rating: { rate: 4.7, count: 180 },
  },
  {
    id: 1002,
    title: "Летнее платье для девочек с цветами",
    price: 22.5,
    description: "Легкое цветочное платье из дышащей ткани для теплых дней.",
    category: "girls clothing",
    image: "/d66e6pjq345uoeq1u0mg.jpg",
    rating: { rate: 4.8, count: 145 },
  },
  {
    id: 1003,
    title: "Уютный худи для малышей",
    price: 26.0,
    description: "Теплый худи с передним карманом и мягкой внутренней отделкой.",
    category: "toddler clothing",
    image: "/d047nvtpb7f46s882adg.jpg",
    rating: { rate: 4.6, count: 95 },
  },
  {
    id: 1004,
    title: "Детские джинсовые комбинезоны",
    price: 31.99,
    description: "Прочные джинсовые комбинезоны с регулируемыми лямками и боковыми пуговицами.",
    category: "unisex kids clothing",
    image: "/d6e1nntv2sjv9oet99q0.jpg",
    rating: { rate: 4.5, count: 132 },
  },
  {
    id: 1005,
    title: "Спортивный комплект шорт для мальчиков",
    price: 19.99,
    description: "Комплект из двух предметов для активных игр и комфорта.",
    category: "boys clothing",
    image: "/d0494lmi4n37npapracg.jpg",
    rating: { rate: 4.4, count: 88 },
  },
  {
    id: 1006,
    title: "Вязаный кардиган для девочек",
    price: 24.99,
    description: "Вязаный кардиган на пуговицах — удобно для школы и прогулок.",
    category: "girls clothing",
    image: "/d18kksb3uvppu2ac7rsg.jpg",
    rating: { rate: 4.9, count: 210 },
  },
  {
    id: 1007,
    title: "Набор детских ромперов, 3 шт.",
    price: 17.49,
    description: "Набор из трех ромперов с кнопками и эластичной посадкой.",
    category: "baby clothing",
    image: "/d1n2nsg9oh61u9a3qiq0.jpg",
    rating: { rate: 4.7, count: 170 },
  },
  {
    id: 1008,
    title: "Детская непромокаемая куртка",
    price: 29.5,
    description: "Водоотталкивающая куртка с капюшоном и светоотражающими деталями.",
    category: "unisex kids clothing",
    image: "/d66e6pjq345uoeq1u0mg.jpg",
    rating: { rate: 4.3, count: 76 },
  },
];

export default products;
